### ISSUE TITLE
Ability to resume caption generation from Microsoft Cognitive Services

### ISSUE THREAD

**Issue by chirantan31** [classtranscribe/WebAPI#34]
Microsoft Cognitive Services is used by ClassTranscribe for automatic caption generation. This process takes about 0.7x the duration of the video. Often this process can get interrupted by a "ServiceTimeout" or "ConnectionFailure" exception, this results in restarting the caption generation. A workaround is to resume from last failure point.

**Comment by angrave** [comment]
This may be nearly finished, now that the time offset of the restart is added to the caption timings. Will test...
https://github.com/classtranscribe/WebAPI/blob/e53313c60e95098a309c107d26561443407f610b/CTCommons/MSTranscription/MSTranscriptionService.cs#L117

**Comment by angrave** [comment]
```txt
taskengine         | 2020-09-28T16:49:44.027815316Z fail: TaskEngine.Tasks.TranscriptionTask[0]
taskengine         | 2020-09-28T16:49:44.027888786Z       Transcription Exception:   at 
taskengine         | 2020-09-28T16:49:44.028047064Z          at Microsoft.EntityFrameworkCore.DbContext.AddRangeAsync(IEnumerable`1 entities, CancellationToken cancellationToken)
taskengine         | 2020-09-28T16:49:44.028065656Z          at TaskEngine.Tasks.TranscriptionTask.OnConsume(String videoId, TaskParameters taskParameters, ClientActiveTasks cleanup) in /src/TaskEngine/Tasks/TranscriptionTask.cs:line 126
taskengine         | 2020-09-28T16:49:44.028081836Z System.InvalidOperationException: The instance of entity type 'Caption' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.


taskengine         | 2020-09-28T16:49:44.028274557Z    at Microsoft.EntityFrameworkCore.DbContext.AddRangeAsync(IEnumerable`1 entities, CancellationToken cancellationToken)
taskengine         | 2020-09-28T16:49:44.028290366Z    at TaskEngine.Tasks.TranscriptionTask.OnConsume(String videoId, TaskParameters taskParameters, ClientActiveTasks cleanup) in /src/TaskEngine/Tasks/TranscriptionTask.cs:line 126
taskengine         | 2020-09-28T16:49:44.201611219Z fail: CTCommons.RabbitMQConnection[0]
taskengine         | 2020-09-28T16:49:44.201706826Z       Error occured in RabbitMQConnection Transcribe for message TaskObject(Data=04dedf60-423b-4ef7-b204-6896644322c8; TaskParameters=TaskParameters(Force = False; Metadata = );
taskengine         | 2020-09-28T16:49:44.201740874Z Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
taskengine         | 2020-09-28T16:49:44.201768233Z  ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "PK_Captions"


Which is here - 
                   if (video.Transcriptions != null && video.Transcriptions.Any())
                    {
                        var oldTranscriptions = video.Transcriptions;
                        var oldCaptions = video.Transcriptions.SelectMany(t => t.Captions); //TODO: Does this find Captions??
                        _context.Captions.RemoveRange(oldCaptions);
                        await _context.SaveChangesAsync();
                        _context.Transcriptions.RemoveRange(oldTranscriptions);
                        await _context.SaveChangesAsync();
                    }

                    // Add the latest transcriptions.
                    await _context.Transcriptions.AddRangeAsync(transcriptions);
                    await _context.SaveChangesAsync(); <<< This line

taskengine         | 2020-09-28T16:49:44.202082943Z    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
taskengine         | 2020-09-28T16:49:44.202107761Z   Exception data:
taskengine         | 2020-09-28T16:49:44.202131835Z     Severity: ERROR
taskengine         | 2020-09-28T16:49:44.202154798Z     SqlState: 23505
taskengine         | 2020-09-28T16:49:44.202177684Z     MessageText: duplicate key value violates unique constraint "PK_Captions"
taskengine         | 2020-09-28T16:49:44.202202315Z     Detail: Key ("Id")=(0db8500a-df34-438d-9e2e-e66393db7f38) already exists.
taskengine         | 2020-09-28T16:49:44.202231429Z     SchemaName: public
taskengine         | 2020-09-28T16:49:44.202256424Z     TableName: Captions
taskengine         | 2020-09-28T16:49:44.202279594Z     ConstraintName: PK_Captions
taskengine         | 2020-09-28T16:49:44.202303441Z     File: nbtinsert.c
taskengine         | 2020-09-28T16:49:44.202327282Z     Line: 534
taskengine         | 2020-09-28T16:49:44.202351272Z     Routine: _bt_check_unique
taskengine         | 2020-09-28T16:49:44.202699537Z    --- End of inner exception stack trace ---
taskengine         | 2020-09-28T16:49:44.202939248Z    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
taskengine         | 2020-09-28T16:49:44.202964350Z    at TaskEngine.Tasks.TranscriptionTask.OnConsume(String videoId, TaskParameters taskParameters, ClientActiveTasks cleanup) in /src/TaskEngine/Tasks/TranscriptionTask.cs:line 137

which is here-
catch (Exception ex)
                {
                    _logger.LogError(ex, "Transcription Exception:" + ex.StackTrace);
                    video.TranscribingAttempts += 1000;
                    await _context.SaveChangesAsync(); <<< HERE
```
So it appears that the Video object still has the Transcription object loaded, which has all of the captions loaded.

Also, this code deletes the Transcription rows? Why not keep them if they already exist?

**Comment by houyuan2** [comment]
Here is why old transcriptions are removed from SQL database:
https://github.com/classtranscribe/WebAPI/blob/7f1789ab7a1c2749a26d2313264cfbd2fa05d252/TaskEngine/Tasks/TranscriptionTask.cs#L67
This function internally would create new captions objects based on the new results from Azure. However, caption objects have an index field, which requires us to know how many caption objects are already in the corresponding transcription object. To resolve this problem, we extract all the old captions from database here:
https://github.com/classtranscribe/WebAPI/blob/7f1789ab7a1c2749a26d2313264cfbd2fa05d252/TaskEngine/Tasks/TranscriptionTask.cs#L58
And pass this dictionary to the function call. Therefore, each time the function returns, it has a complete list of captions. To avoid duplication, we need to remove old captions and transcriptions from the database.

**Comment by houyuan2** [comment]
If the problem is about race conditions on the DB object, maybe creating a new instance in TranscriptionTask can solve the problem?

**Comment by angrave** [comment]
After talking to Chirantan. This is likely a problem of soft deletes. Before adding the adding the captions in we should set their IDs to null, so that new rows are created.
