### ISSUE TITLE
Database connections shared across multiple concurrent transcription tasks

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#91]
Most Tasks were already creating a DB connection on the fly with
``` using (context = CTDBContext)```
The Transcription task was not; this leads to race conditions and update errors which are apparent in the taskengine log.

Relevant commit -
https://github.com/classtranscribe/WebAPI/commit/d098fd5947043f48b8c10c96c9a2f9fc0ab75982

protected async override Task OnConsume(string videoId, TaskParameters taskParameters)
        { using (var _context = CTDbContext.CreateDbContext()) {

example error log -
taskengine         |       Error occured in RabbitMQConnection Transcribe for message TaskObject(Data=052b9ac6-0d81-4e63-a203-d3f888a771cc; TaskParameters=TaskParameters(Force = False; Metadata = );
taskengine         | System.InvalidOperationException: A second operation started on this context before a previous operation completed.
 This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext,
  see https://go.microsoft.com/fwlink/?linkid=2097913.
taskengine         |    at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
...
taskengine         |    at TaskEngine.Tasks.TranscriptionTask.OnConsume(String videoId, TaskParameters taskParameters) 
in /src/TaskEngine/Tasks/TranscriptionTask.cs:line 52
taskengine         |    at CTCommons.RabbitMQConnection.<>c__DisplayClass8_0`1.<<ConsumeTask>b__0>d.MoveNext() in /src/CTCommons/RabbitMQ/RabbitMQConnection.cs:line 104

**Comment by angrave** [comment]
Scoped contexts are now used in all tasks e.g. (commit d098fd5947043f48b8c10c96c9a2f9fc0ab75982). However the above error can still occur when restarting transcriptions
