### ISSUE TITLE
TaskEngine Race condition for manually uploaded files.

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#92]
I just tried uploading 5 videos to a new playlist on -dev. The are all very short (3seconds) recorded using Zoom as a local mp4.  "This is video 1" "This is video 2" etc; Only the 5th video made it to the playlist, even after I refreshed the page. However future attempts worked fine. Parts of the log that appear relevant
```txt
taskengine         | 2020-09-23T20:42:25.517947163Z fail: TaskEngine.Tasks.DownloadMediaTask[0]
taskengine         | 2020-09-23T20:42:25.517987186Z       DownloadLocalPlaylist failed. mediaId 891edecd-5312-4e4b-8277-d0d9d5fac371
taskengine         | 2020-09-23T20:42:25.518001689Z System.IO.FileNotFoundException: Could not find file '/data/OF4AP98FR23H'.
taskengine         | 2020-09-23T20:42:25.518014610Z File name: '/data/OF4AP98FR23H'
taskengine         | 2020-09-23T20:42:25.518028095Z    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
taskengine         | 2020-09-23T20:42:25.518041374Z    at System.IO.File.Move(String sourceFileName, String destFileName)
taskengine         | 2020-09-23T20:42:25.518054185Z    at ClassTranscribeDatabase.Models.FileRecord.GetNewFileRecord(String filepath, String ext) in /src/ClassTranscribeDatabase/Models/FileRecord.cs:line 33
taskengine         | 2020-09-23T20:42:25.518067570Z    at TaskEngine.Tasks.DownloadMediaTask.DownloadLocalPlaylist(Media media) in /src/TaskEngine/Tasks/DownloadMediaTask.cs:line 237
taskengine         | 2020-09-23T20:42:25.646355898Z fail: CTCommons.RabbitMQConnection[0]
taskengine         | 2020-09-23T20:42:25.646396864Z       Error occured in RabbitMQConnection DownloadMedia for message TaskObject(Data=891edecd-5312-4e4b-8277-d0d9d5fac371; TaskParameters=TaskParameters(Force = False; Metadata = );
taskengine         | 2020-09-23T20:42:25.646412192Z System.Exception: DownloadMediaTask failed for mediaId 891edecd-5312-4e4b-8277-d0d9d5fac371
```

```txt
taskengine         | 2020-09-23T20:42:25.974389435Z        [x] DownloadMedia Received TaskObject(Data=9df32c4d-8b9b-4ad4-be79-da631045438e; TaskParameters=TaskParameters(Force = False; Metadata = );
taskengine         | 2020-09-23T20:42:25.980614133Z info: TaskEngine.Tasks.DownloadMediaTask[0]
taskengine         | 2020-09-23T20:42:25.980686236Z       ConsumingCastle.Proxies.MediaProxy
taskengine         | 2020-09-23T20:42:25.981420773Z fail: TaskEngine.Tasks.DownloadMediaTask[0]
taskengine         | 2020-09-23T20:42:25.981452815Z       DownloadLocalPlaylist failed. mediaId 9df32c4d-8b9b-4ad4-be79-da631045438e
taskengine         | 2020-09-23T20:42:25.981466851Z System.IO.FileNotFoundException: Could not find file '/data/MCWLSGBKZHS9'.
taskengine         | 2020-09-23T20:42:25.981480331Z File name: '/data/MCWLSGBKZHS9'
taskengine         | 2020-09-23T20:42:25.981493182Z    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
taskengine         | 2020-09-23T20:42:25.981505960Z    at System.IO.File.Move(String sourceFileName, String destFileName)
taskengine         | 2020-09-23T20:42:25.981519291Z    at ClassTranscribeDatabase.Models.FileRecord.GetNewFileRecord(String filepath, String ext) in /src/ClassTranscribeDatabase/Models/FileRecord.cs:line 33
taskengine         | 2020-09-23T20:42:25.981533484Z    at TaskEngine.Tasks.DownloadMediaTask.DownloadLocalPlaylist(Media media) in /src/TaskEngine/Tasks/DownloadMediaTask.cs:line 237
taskengine         | 2020-09-23T20:42:25.982630181Z info: TaskEngine.Tasks.ProcessVideoTask[0]
taskengine         | 2020-09-23T20:42:25.982666442Z       ConsumingCastle.Proxies.VideoProxy
taskengine         | 2020-09-23T20:42:25.994436797Z fail: CTCommons.RabbitMQConnection[0]
taskengine         | 2020-09-23T20:42:25.994477664Z       Error occured in RabbitMQConnection DownloadMedia for message TaskObject(Data=9df32c4d-8b9b-4ad4-be79-da631045438e; TaskParameters=TaskParameters(Force = False; Metadata = );
taskengine         | 2020-09-23T20:42:25.994817636Z System.Exception: DownloadMediaTask failed for mediaId 9df32c4d-8b9b-4ad4-be79-da631045438e
taskengine         | 2020-09-23T20:42:25.994865290Z    at TaskEngine.Tasks.DownloadMediaTask.OnConsume(String mediaId, TaskParameters taskParameters) in /src/TaskEngine/Tasks/DownloadMediaTask.cs:line 65
taskengine         | 2020-09-23T20:42:25.996048953Z    at CTCommons.RabbitMQConnection.<>c__DisplayClass8_0`1.<<ConsumeTask>b__0>d.MoveNext() in /src/CTCommons/RabbitMQ/RabbitMQConnection.cs:line 104
taskengine         | 2020-09-23T20:42:25.996340493Z info: CTCommons.RabbitMQConnection[0]
taskengine         | 2020-09-23T20:42:25.996372410Z        [x] DownloadMedia Done TaskObject(Data=9df32c4d-8b9b-4ad4-be79-da631045438e; TaskParameters=TaskParameters(Force = False; Metadata = );
```

**Comment by angrave** [comment]
The fix for this is to not generate a task but to perform this directly in the webapi and perform directly as part of the upload code. It may make sense to refactor some of the existing task code (e.g. generating an appropriate name for a video) into a common project, so it can be used by both the webapi and a task
