### ISSUE TITLE
Prevent/Review Duplicate Transcription when video appears twice in same playlist 

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#93]
on -dev, A manual upload playlist had multiple entries of the same mp4 video. In the logs -
```txt
taskengine         | 2020-09-23T21:17:20.694417274Z       Stop recognition.
taskengine         | 2020-09-23T21:17:21.767143311Z fail: TaskEngine.Tasks.TranscriptionTask[0]
taskengine         | 2020-09-23T21:17:21.767229753Z       Transcription Exception:   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
taskengine         | 2020-09-23T21:17:21.767261793Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
taskengine         | 2020-09-23T21:17:21.767287826Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
taskengine         | 2020-09-23T21:17:21.767314533Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
taskengine         | 2020-09-23T21:17:21.767340763Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityStateAsync(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767368708Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintActionAsync(EntityEntryGraphNode`1 node, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767394094Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767420988Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767447355Z          at Microsoft.EntityFrameworkCore.DbContext.AddRangeAsync(IEnumerable`1 entities, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767470505Z          at TaskEngine.Tasks.TranscriptionTask.OnConsume(String videoId, TaskParameters taskParameters) in /src/TaskEngine/Tasks/TranscriptionTask.cs:line 113
taskengine         | 2020-09-23T21:17:21.767497730Z System.InvalidOperationException: The instance of entity type 'Caption' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
taskengine         | 2020-09-23T21:17:21.767515693Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
taskengine         | 2020-09-23T21:17:21.767529456Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
taskengine         | 2020-09-23T21:17:21.767563141Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
taskengine         | 2020-09-23T21:17:21.767578217Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
taskengine         | 2020-09-23T21:17:21.767592264Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityStateAsync(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767606737Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintActionAsync(EntityEntryGraphNode`1 node, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767620650Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767635010Z    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767649082Z    at Microsoft.EntityFrameworkCore.DbContext.AddRangeAsync(IEnumerable`1 entities, CancellationToken cancellationToken)
taskengine         | 2020-09-23T21:17:21.767663209Z    at TaskEngine.Tasks.TranscriptionTask.OnConsume(String videoId, TaskParameters taskParameters) in /src/TaskEngine/Tasks/TranscriptionTask.cs:line 113
```

**Comment by angrave** [comment]
This was on -dev. It is possible that some containers werent started with root privileges. So treat this bug report as suspicious.
